import type { CardType, PatternStyle, ProgressStyle, LabelFormat, StampGridConfig } from "./card-design"

// ─── Types ──────────────────────────────────────────────

export type BusinessCategory = "cafe" | "fine-dining" | "casual" | "bar" | "bakery" | "general"

export type CardTemplate = {
  id: string
  name: string
  description: string
  category: BusinessCategory
  tags: string[]
  design: {
    cardType?: CardType // defaults to "STAMP" if undefined (backward compat)
    showStrip: boolean
    primaryColor: string
    secondaryColor: string
    textColor: string
    patternStyle: PatternStyle
    progressStyle: ProgressStyle
    labelFormat: LabelFormat
    palettePreset: string | null
    useStampGrid?: boolean
    stampGridConfig?: StampGridConfig
    stripColor1?: string | null
    stripColor2?: string | null
    stripFill?: "flat" | "gradient"
    patternColor?: string | null
  }
}

// ─── Categories ─────────────────────────────────────────

export const TEMPLATE_CATEGORIES: { id: BusinessCategory | "all"; name: string }[] = [
  { id: "all", name: "All" },
  { id: "cafe", name: "Cafe" },
  { id: "fine-dining", name: "Fine Dining" },
  { id: "casual", name: "Casual" },
  { id: "bar", name: "Bar" },
  { id: "bakery", name: "Bakery" },
  { id: "general", name: "General" },
]

// ─── Templates ──────────────────────────────────────────

export const CARD_TEMPLATES: CardTemplate[] = [
  // ── STAMP: Existing 10 ──────────────────────────────────

  {
    id: "cafe-warm-brew",
    name: "Warm Brew",
    description: "Earthy tones with a warm gradient — perfect for coffee shops",
    category: "cafe",
    tags: ["coffee", "warm", "cozy"],
    design: {
      showStrip: true,
      primaryColor: "#3e2723",
      secondaryColor: "#a1887f",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "STAMPS",
      labelFormat: "TITLE_CASE",
      palettePreset: "espresso",
    },
  },

  {
    id: "cafe-minimal",
    name: "Clean Roast",
    description: "Minimal and modern — let the brand speak for itself",
    category: "cafe",
    tags: ["minimal", "modern", "clean"],
    design: {
      showStrip: false,
      primaryColor: "#1a1a1a",
      secondaryColor: "#e0e0e0",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: "charcoal",
    },
  },

  {
    id: "fine-noir",
    name: "Noir",
    description: "Dark and luxurious — for premium dining experiences",
    category: "fine-dining",
    tags: ["dark", "luxury", "premium"],
    design: {
      showStrip: true,
      primaryColor: "#0a0a0a",
      secondaryColor: "#4a4a4a",
      textColor: "#f5f5f5",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "fine-gold",
    name: "Gold Reserve",
    description: "Sophisticated black and gold for an exclusive feel",
    category: "fine-dining",
    tags: ["gold", "sophisticated", "exclusive"],
    design: {
      showStrip: true,
      primaryColor: "#1a1a2e",
      secondaryColor: "#c9a96e",
      textColor: "#f5f0e8",
      patternStyle: "GEOMETRIC",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "casual-bright",
    name: "Sunny Side",
    description: "Bright and fun — bring energy to every visit",
    category: "casual",
    tags: ["bright", "fun", "energetic"],
    design: {
      showStrip: true,
      primaryColor: "#f57c00",
      secondaryColor: "#fff176",
      textColor: "#ffffff",
      patternStyle: "DOTS",
      progressStyle: "STAMPS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "casual-fresh",
    name: "Fresh & Easy",
    description: "Light and airy — a clean look that works everywhere",
    category: "casual",
    tags: ["light", "airy", "fresh"],
    design: {
      showStrip: false,
      primaryColor: "#ffffff",
      secondaryColor: "#4caf50",
      textColor: "#1a1a1a",
      patternStyle: "NONE",
      progressStyle: "CIRCLES",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "bar-neon",
    name: "Neon Nights",
    description: "Moody vibes with neon accents — made for nightlife",
    category: "bar",
    tags: ["moody", "neon", "nightlife"],
    design: {
      showStrip: true,
      primaryColor: "#0d0d0d",
      secondaryColor: "#e040fb",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "CIRCLES",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "bar-craft",
    name: "Craft House",
    description: "Industrial and warm — for craft beer bars and gastropubs",
    category: "bar",
    tags: ["industrial", "craft", "amber"],
    design: {
      showStrip: true,
      primaryColor: "#263238",
      secondaryColor: "#ffb300",
      textColor: "#ffffff",
      patternStyle: "GEOMETRIC",
      progressStyle: "SQUARES",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "bakery-sweet",
    name: "Sweet Pastels",
    description: "Soft and welcoming — ideal for bakeries and patisseries",
    category: "bakery",
    tags: ["soft", "pastel", "welcoming"],
    design: {
      showStrip: true,
      primaryColor: "#f8bbd0",
      secondaryColor: "#fff8e1",
      textColor: "#4e342e",
      patternStyle: "DOTS",
      progressStyle: "STARS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "general-slate",
    name: "Slate Modern",
    description: "Neutral and professional — works for any business",
    category: "general",
    tags: ["neutral", "professional", "universal"],
    design: {
      showStrip: false,
      primaryColor: "#334155",
      secondaryColor: "#94a3b8",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: "slate",
    },
  },

  // ── STAMP: 5 New ─────────────────────────────────────────

  {
    id: "cafe-matcha",
    name: "Matcha Garden",
    description: "Soft greens and cream — serene vibes for specialty cafes",
    category: "cafe",
    tags: ["matcha", "green", "zen", "specialty"],
    design: {
      showStrip: true,
      primaryColor: "#2d6a4f",
      secondaryColor: "#b7e4c7",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "STAMPS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "casual-retro",
    name: "Retro Diner",
    description: "Vintage checkerboard energy — nostalgic and bold",
    category: "casual",
    tags: ["retro", "vintage", "bold", "diner"],
    design: {
      showStrip: true,
      primaryColor: "#b71c1c",
      secondaryColor: "#ffeb3b",
      textColor: "#ffffff",
      patternStyle: "CROSSHATCH",
      progressStyle: "SQUARES",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "bar-whiskey",
    name: "Old Fashioned",
    description: "Deep amber and wood tones — for whiskey bars and speakeasies",
    category: "bar",
    tags: ["whiskey", "amber", "dark", "premium"],
    design: {
      showStrip: true,
      primaryColor: "#3e1a00",
      secondaryColor: "#bf8c5a",
      textColor: "#f5e6d3",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "bakery-artisan",
    name: "Artisan Loaf",
    description: "Warm kraft-paper tones — rustic and handcrafted feel",
    category: "bakery",
    tags: ["artisan", "rustic", "bread", "craft"],
    design: {
      showStrip: false,
      primaryColor: "#5d4037",
      secondaryColor: "#d7ccc8",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "STAMPS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "fine-blush",
    name: "Rose & Ivory",
    description: "Soft blush and ivory — modern fine dining with feminine elegance",
    category: "fine-dining",
    tags: ["blush", "elegant", "feminine", "modern"],
    design: {
      showStrip: true,
      primaryColor: "#880e4f",
      secondaryColor: "#f8bbd0",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "CIRCLES",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  // ── POINTS: 7 Templates ──────────────────────────────────

  {
    id: "points-progress-pro",
    name: "Progress Pro",
    description: "Energetic green gradient with a thick bar — built for casual dining loyalty",
    category: "casual",
    tags: ["progress", "green", "energy", "gradient"],
    design: {
      showStrip: true,
      primaryColor: "#1b5e20",
      secondaryColor: "#69f0ae",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "points-sleek-track",
    name: "Sleek Track",
    description: "Dark and refined with a thin progress bar — versatile for any venue",
    category: "general",
    tags: ["dark", "minimal", "thin", "sleek"],
    design: {
      showStrip: false,
      primaryColor: "#121212",
      secondaryColor: "#e0e0e0",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "points-neon-progress",
    name: "Neon Progress",
    description: "Neon pink and purple bar — electric nightlife energy",
    category: "bar",
    tags: ["neon", "bar", "nightlife", "electric"],
    design: {
      showStrip: true,
      primaryColor: "#0d0d0d",
      secondaryColor: "#e040fb",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "points-nature-path",
    name: "Nature Path",
    description: "Earthy greens and warm browns — grounded and organic cafe feel",
    category: "cafe",
    tags: ["earthy", "organic", "green", "natural"],
    design: {
      showStrip: false,
      primaryColor: "#33691e",
      secondaryColor: "#dcedc8",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "points-ice-cream-dash",
    name: "Ice Cream Dash",
    description: "Pastel gradient bar — playful and sweet for dessert counters",
    category: "bakery",
    tags: ["pastel", "sweet", "ice cream", "playful"],
    design: {
      showStrip: true,
      primaryColor: "#fce4ec",
      secondaryColor: "#e1bee7",
      textColor: "#4a148c",
      patternStyle: "DOTS",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "points-power-meter",
    name: "Power Meter",
    description: "Bold red and orange bar — high-energy for fast-casual brands",
    category: "casual",
    tags: ["bold", "red", "orange", "energy", "fast-casual"],
    design: {
      showStrip: true,
      primaryColor: "#b71c1c",
      secondaryColor: "#ff8f00",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "points-zen-flow",
    name: "Zen Flow",
    description: "Minimal thin bar with muted tones — refined for fine dining",
    category: "fine-dining",
    tags: ["minimal", "zen", "muted", "refined"],
    design: {
      showStrip: false,
      primaryColor: "#1c1c1e",
      secondaryColor: "#8e8e93",
      textColor: "#f2f2f7",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  // ── TIER: 5 Templates ────────────────────────────────────

  {
    id: "tier-gold-club",
    name: "Gold Club",
    description: "Classic black and gold shield — the mark of a premium member",
    category: "fine-dining",
    tags: ["gold", "shield", "premium", "classic"],
    design: {
      cardType: "TIER",
      showStrip: true,
      primaryColor: "#1a1a2e",
      secondaryColor: "#c9a96e",
      textColor: "#f5f0e8",
      patternStyle: "GEOMETRIC",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "tier-vip-lounge",
    name: "VIP Lounge",
    description: "Dark purple with a star badge — for bars with elite regulars",
    category: "bar",
    tags: ["vip", "dark", "purple", "star", "nightlife"],
    design: {
      cardType: "TIER",
      showStrip: true,
      primaryColor: "#1a0030",
      secondaryColor: "#9c27b0",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "tier-elite-status",
    name: "Elite Status",
    description: "Silver and navy with a circle badge — professional and versatile",
    category: "general",
    tags: ["silver", "navy", "circle", "professional"],
    design: {
      cardType: "TIER",
      showStrip: false,
      primaryColor: "#1a237e",
      secondaryColor: "#90caf9",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "tier-crown-tier",
    name: "Crown Tier",
    description: "Burgundy and gold shield — regal and aspirational",
    category: "fine-dining",
    tags: ["burgundy", "gold", "regal", "shield", "exclusive"],
    design: {
      cardType: "TIER",
      showStrip: true,
      primaryColor: "#4a0010",
      secondaryColor: "#c9a96e",
      textColor: "#f5f0e8",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "tier-level-up",
    name: "Level Up",
    description: "Bold gradient with a star badge — gamified loyalty for casual spots",
    category: "casual",
    tags: ["gamified", "gradient", "star", "bold", "progress"],
    design: {
      cardType: "TIER",
      showStrip: true,
      primaryColor: "#1565c0",
      secondaryColor: "#00bfa5",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  // ── COUPON: 5 Templates ──────────────────────────────────

  {
    id: "coupon-flash-deal",
    name: "Flash Deal",
    description: "Bold red ticket style — urgent and attention-grabbing",
    category: "general",
    tags: ["bold", "red", "urgent", "deal", "ticket"],
    design: {
      cardType: "COUPON",
      showStrip: true,
      primaryColor: "#c62828",
      secondaryColor: "#ffffff",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "coupon-happy-hour",
    name: "Happy Hour",
    description: "Neon ticket style — glowing deals for bar promotions",
    category: "bar",
    tags: ["neon", "bar", "happy hour", "ticket", "nightlife"],
    design: {
      cardType: "COUPON",
      showStrip: true,
      primaryColor: "#0d0d0d",
      secondaryColor: "#00e676",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "coupon-sweet-treat",
    name: "Sweet Treat",
    description: "Pastel bold style — irresistible offers for bakeries",
    category: "bakery",
    tags: ["pastel", "sweet", "bakery", "bold"],
    design: {
      cardType: "COUPON",
      showStrip: true,
      primaryColor: "#f06292",
      secondaryColor: "#fff8e1",
      textColor: "#4e342e",
      patternStyle: "DOTS",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "coupon-first-timer",
    name: "First Timer",
    description: "Warm minimal style — a welcoming offer for new cafe visitors",
    category: "cafe",
    tags: ["warm", "minimal", "welcome", "cafe", "first visit"],
    design: {
      cardType: "COUPON",
      showStrip: false,
      primaryColor: "#fff8f0",
      secondaryColor: "#795548",
      textColor: "#3e2723",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "coupon-vip-offer",
    name: "VIP Offer",
    description: "Dark and bold — an exclusive offer for fine dining guests",
    category: "fine-dining",
    tags: ["vip", "dark", "exclusive", "bold", "fine-dining"],
    design: {
      cardType: "COUPON",
      showStrip: true,
      primaryColor: "#0a0a0a",
      secondaryColor: "#c9a96e",
      textColor: "#f5f0e8",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  {
    id: "coupon-simple-offer",
    name: "Simple Offer",
    description: "Clean and minimal — a straightforward discount for any venue",
    category: "general",
    tags: ["simple", "clean", "minimal", "offer"],
    design: {
      cardType: "COUPON",
      showStrip: false,
      primaryColor: "#212121",
      secondaryColor: "#757575",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: "charcoal",
    },
  },

  {
    id: "tier-modern-member",
    name: "Modern Member",
    description: "Dark teal and contemporary — a fresh take on membership cards",
    category: "general",
    tags: ["modern", "teal", "dark", "fresh", "member"],
    design: {
      cardType: "TIER",
      showStrip: false,
      primaryColor: "#0d3b3b",
      secondaryColor: "#4db6ac",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
    },
  },

  // ── GENERAL / MULTI-TYPE: 3 Templates ───────────────────

  {
    id: "general-universal-clean",
    name: "Universal Clean",
    description: "Ultra minimal white card — works for any brand, any context",
    category: "general",
    tags: ["minimal", "white", "universal", "clean", "blank"],
    design: {
      showStrip: false,
      primaryColor: "#ffffff",
      secondaryColor: "#f5f5f5",
      textColor: "#111111",
      patternStyle: "NONE",
      progressStyle: "STAMPS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "general-restaurant-classic",
    name: "Restaurant Classic",
    description: "Serif type and deep red — a timeless traditional loyalty card",
    category: "general",
    tags: ["traditional", "classic", "serif", "red", "timeless"],
    design: {
      showStrip: true,
      primaryColor: "#8b0000",
      secondaryColor: "#f5f0e8",
      textColor: "#f5f0e8",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },

  {
    id: "general-modern-flex",
    name: "Modern Flex",
    description: "Contemporary gradient with a points bar — adapts to any modern business",
    category: "general",
    tags: ["modern", "gradient", "points", "flexible", "contemporary"],
    design: {
      showStrip: true,
      primaryColor: "#1e3a5f",
      secondaryColor: "#00b4d8",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
    },
  },
  // ── STAMP GRID: 4 Templates ────────────────────────────────

  {
    id: "stamp-grid-coffee",
    name: "Coffee Stamps",
    description: "Classic coffee cup stamps on a dark background — the digital stamp card",
    category: "cafe",
    tags: ["coffee", "stamps", "grid", "visual", "cafe"],
    design: {
      showStrip: true,
      primaryColor: "#3e2723",
      secondaryColor: "#a1887f",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: "espresso",
      useStampGrid: true,
      stampGridConfig: {
        stampIcon: "coffee",
        customStampIconUrl: null,
        customRewardIconUrl: null,
        customEmptyIconUrl: null,
        useUniformIcon: false,
        emptyNumberColor: null,
        emptyNumberScale: 0.35,
        emptySlotOpacity: 0.35,
        emptySlotColor: null,
        emptySlotBg: null,
        rewardSlotColor: null,
        rewardSlotBg: null,
        rewardIcon: "reward-star",
        stampShape: "circle",
        filledStyle: "icon",
        stampIconScale: 0.6,
        useStripBackground: false,
      },
    },
  },

  {
    id: "stamp-grid-pizza",
    name: "Pizza Tracker",
    description: "Rounded pizza stamps — track your way to a free slice",
    category: "casual",
    tags: ["pizza", "stamps", "grid", "fun", "casual"],
    design: {
      showStrip: true,
      primaryColor: "#b71c1c",
      secondaryColor: "#ffeb3b",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
      useStampGrid: true,
      stampGridConfig: {
        stampIcon: "pizza",
        customStampIconUrl: null,
        customRewardIconUrl: null,
        customEmptyIconUrl: null,
        useUniformIcon: false,
        emptyNumberColor: null,
        emptyNumberScale: 0.35,
        emptySlotOpacity: 0.35,
        emptySlotColor: null,
        emptySlotBg: null,
        rewardSlotColor: null,
        rewardSlotBg: null,
        rewardIcon: "sparkles",
        stampShape: "rounded-square",
        filledStyle: "icon-with-border",
        stampIconScale: 0.6,
        useStripBackground: false,
      },
    },
  },

  {
    id: "stamp-grid-burger",
    name: "Burger Badges",
    description: "Bold square burger badges — earn your way to a free meal",
    category: "casual",
    tags: ["burger", "stamps", "grid", "bold", "badges"],
    design: {
      showStrip: true,
      primaryColor: "#1a1a1a",
      secondaryColor: "#ff8f00",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
      useStampGrid: true,
      stampGridConfig: {
        stampIcon: "beef",
        customStampIconUrl: null,
        customRewardIconUrl: null,
        customEmptyIconUrl: null,
        useUniformIcon: false,
        emptyNumberColor: null,
        emptyNumberScale: 0.35,
        emptySlotOpacity: 0.35,
        emptySlotColor: null,
        emptySlotBg: null,
        rewardSlotColor: null,
        rewardSlotBg: null,
        rewardIcon: "trophy",
        stampShape: "square",
        filledStyle: "icon",
        stampIconScale: 0.6,
        useStripBackground: false,
      },
    },
  },

  {
    id: "stamp-grid-drinks",
    name: "Drink Collector",
    description: "Collect drink stamps with a clean minimal look",
    category: "bar",
    tags: ["drinks", "stamps", "grid", "minimal", "bar"],
    design: {
      showStrip: true,
      primaryColor: "#0d0d0d",
      secondaryColor: "#e040fb",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: null,
      useStampGrid: true,
      stampGridConfig: {
        stampIcon: "cup-soda",
        customStampIconUrl: null,
        customRewardIconUrl: null,
        customEmptyIconUrl: null,
        useUniformIcon: false,
        emptyNumberColor: null,
        emptyNumberScale: 0.35,
        emptySlotOpacity: 0.35,
        emptySlotColor: null,
        emptySlotBg: null,
        rewardSlotColor: null,
        rewardSlotBg: null,
        rewardIcon: "gift",
        stampShape: "circle",
        filledStyle: "solid",
        stampIconScale: 0.6,
        useStripBackground: false,
      },
    },
  },

  {
    id: "stamp-grid-fine-dining",
    name: "Dining Collection",
    description: "Elegant circular stamps for premium dining — refined and understated",
    category: "fine-dining",
    tags: ["fine-dining", "stamps", "grid", "elegant", "premium"],
    design: {
      showStrip: true,
      primaryColor: "#1a1a2e",
      secondaryColor: "#c9b037",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
      useStampGrid: true,
      stampGridConfig: {
        stampIcon: "utensils-crossed",
        customStampIconUrl: null,
        customRewardIconUrl: null,
        customEmptyIconUrl: null,
        useUniformIcon: false,
        emptyNumberColor: null,
        emptyNumberScale: 0.35,
        emptySlotOpacity: 0.35,
        emptySlotColor: null,
        emptySlotBg: null,
        rewardSlotColor: null,
        rewardSlotBg: null,
        rewardIcon: "crown",
        stampShape: "circle",
        filledStyle: "icon",
        stampIconScale: 0.55,
        useStripBackground: false,
      },
    },
  },

  {
    id: "stamp-grid-bakery",
    name: "Sweet Stamps",
    description: "Soft rounded cookie stamps — warm and inviting for bakeries",
    category: "bakery",
    tags: ["bakery", "stamps", "grid", "sweet", "pastry"],
    design: {
      showStrip: true,
      primaryColor: "#f5e6d3",
      secondaryColor: "#8d6e63",
      textColor: "#3e2723",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "TITLE_CASE",
      palettePreset: null,
      useStampGrid: true,
      stampGridConfig: {
        stampIcon: "cookie",
        customStampIconUrl: null,
        customRewardIconUrl: null,
        customEmptyIconUrl: null,
        useUniformIcon: false,
        emptyNumberColor: null,
        emptyNumberScale: 0.35,
        emptySlotOpacity: 0.35,
        emptySlotColor: null,
        emptySlotBg: null,
        rewardSlotColor: null,
        rewardSlotBg: null,
        rewardIcon: "gift",
        stampShape: "rounded-square",
        filledStyle: "icon-with-border",
        stampIconScale: 0.6,
        useStripBackground: false,
      },
    },
  },

  {
    id: "stamp-grid-general",
    name: "Loyalty Stamps",
    description: "Clean versatile stamp card — works for any business",
    category: "general",
    tags: ["general", "stamps", "grid", "versatile", "universal"],
    design: {
      showStrip: true,
      primaryColor: "#334155",
      secondaryColor: "#94a3b8",
      textColor: "#ffffff",
      patternStyle: "NONE",
      progressStyle: "NUMBERS",
      labelFormat: "UPPERCASE",
      palettePreset: "slate",
      useStampGrid: true,
      stampGridConfig: {
        stampIcon: "heart",
        customStampIconUrl: null,
        customRewardIconUrl: null,
        customEmptyIconUrl: null,
        useUniformIcon: false,
        emptyNumberColor: null,
        emptyNumberScale: 0.35,
        emptySlotOpacity: 0.35,
        emptySlotColor: null,
        emptySlotBg: null,
        rewardSlotColor: null,
        rewardSlotBg: null,
        rewardIcon: "gift",
        stampShape: "circle",
        filledStyle: "icon",
        stampIconScale: 0.6,
        useStripBackground: false,
      },
    },
  },
]

// ─── Helpers ─────────────────────────────────────────────

/** Find a template by ID */
export function getTemplateById(id: string): CardTemplate | undefined {
  return CARD_TEMPLATES.find((t) => t.id === id)
}
